version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    container_name: web
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
    env_file:
      - ./movies_admin/config/.env

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
