version: '2.2'
services:
  logstash:
    image: logstash:7.10.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticlogstash:9200"
    ports:
      - "5044:5044/udp"
    depends_on:
      - elasticlogstash
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  filebeat:
    image: elastic/filebeat:7.17.5
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - nginx
      - logstash
      - elasticlogstash
      - kibana
    links:
      - logstash

  
  elasticlogstash:  # Отдельный от полнотекстового поиска инстанс
    image: elasticsearch:7.17.5
    environment:
      # Указываем ES запуститься в одном экземпляре
      - discovery.type=single-node
      # Ограничим использование памяти
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    volumes:
      - /tmp/esdata:/tmp/elasticlogstash/data

  kibana:
    image: kibana:7.17.5
    ports:
      - "5601:5601" 
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticlogstash:9200"]'
    depends_on:
      - elasticlogstash
